import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { ChakraUIProvider } from "@/providers/ChakraUIProvider";
import { getCurrentScheme } from "@/utils/getCurrentTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const color = await getCurrentScheme();

  return (
    <ClerkProvider
      appearance={{
        baseTheme: color === "dark" ? dark : undefined,
      }}
    >
      <html lang="en" className={color === "dark" ? "dark" : "light"}>
        <body className={inter.className}>
          <ChakraUIProvider>{children}</ChakraUIProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
